name: Continuous Integration

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up readline and libhistory for tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Run `build` with only library
        run: zig build -Dtools=false

      - name: Run `build` with tools
        run: zig build
